/**
 * skills/self-improving-engine.ts
 * Orchestrates the self-improving pipeline per completed turn.
 */

import { loadSkillFromFile } from './loader';
import type { Skill } from './loader';
import type { SkillRegistry } from './registry';
import type { SkillExtractionInput } from './skill-extractor';
import { SkillExtractor } from './skill-extractor';
import { SkillWriter } from './skill-writer';
import { SkillQualityTracker } from './skill-quality-tracker';
import { SkillEvaluator } from './skill-evaluator';
import type { EvaluationReport } from './skill-evaluator';
import { createLogger } from '../utils/logger';

const logger = createLogger('skills:self-improving');

export interface SelfImprovingStatus {
  autoSkillsDir: string;
  qualityFilePath: string;
  evaluationThreshold: number;
  taskCounter: number;
  autoSkillsCount: number;
  activeAutoSkillsCount: number;
}

export interface SelfImprovingSkillStatus {
  id: string;
  name: string;
  enabled: boolean;
  usageCount: number;
  successCount: number;
  failureCount: number;
  successRate: number;
  filePath: string;
}

function isAutoGenerated(skill: Skill): boolean {
  return skill.frontmatter.auto_generated === true || skill.frontmatter.raw['auto_generated'] === 'true';
}

export class SelfImprovingEngine {
  constructor(
    private readonly extractor: SkillExtractor,
    private readonly writer: SkillWriter,
    private readonly tracker: SkillQualityTracker,
    private readonly evaluator: SkillEvaluator,
    private readonly registry: SkillRegistry,
    private readonly skillsBaseDir = 'skills'
  ) {}

  async processCompletedTurn(input: SkillExtractionInput): Promise<void> {
    try {
      const extracted = await this.extractor.extract(input);

      if (extracted) {
        const filePath = await this.writer.write(extracted);
        if (filePath) {
          const loaded = await loadSkillFromFile(filePath);
          if (loaded.ok) {
            this.registry.registerAndActivate(loaded.value);
            await this.tracker.registerSkill(loaded.value.id, loaded.value.name, filePath);
            logger.info('new skill extracted and registered', {
              id: loaded.value.id,
              name: loaded.value.name,
              filePath,
            });
          } else {
            logger.warn('extracted skill could not be loaded', {
              filePath,
              error: loaded.error.message,
            });
          }
        }
      }

      await this.tracker.recordTaskCompletion(input.activeSkillsUsed ?? [], true);

      if (await this.tracker.shouldRunEvaluation()) {
        logger.info('running self-evaluation pass');
        const report = await this.evaluator.evaluate(this.registry.all());
        logger.info('self-evaluation complete', { ...report });
        await this.registry.load({ skillsDir: this.skillsBaseDir });
        await this.tracker.resetEvaluationCounter();
      }
    } catch (err) {
      logger.warn('self-improving processing failed', {
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  async getStatus(): Promise<SelfImprovingStatus> {
    await this.tracker.load();
    const autoSkillFiles = await this.writer.listAutoSkills();

    return {
      autoSkillsDir: this.writer.directory,
      qualityFilePath: this.tracker.qualityFilePath,
      evaluationThreshold: this.tracker.threshold,
      taskCounter: this.tracker.getTaskCounter(),
      autoSkillsCount: autoSkillFiles.length,
      activeAutoSkillsCount: this.registry.activeSkills().filter(isAutoGenerated).length,
    };
  }

  async listAutoSkillStats(): Promise<SelfImprovingSkillStatus[]> {
    await this.tracker.load();
    const rows: SelfImprovingSkillStatus[] = [];

    for (const filePath of await this.writer.listAutoSkills()) {
      const loaded = await loadSkillFromFile(filePath);
      if (!loaded.ok) continue;

      const skill = loaded.value;
      const stats = this.tracker.getSkillStats(skill.id);
      const usageCount = stats?.usageCount ?? 0;
      const successCount = stats?.successCount ?? 0;
      const failureCount = stats?.failureCount ?? 0;

      rows.push({
        id: skill.id,
        name: skill.name,
        enabled: skill.frontmatter.enabled,
        usageCount,
        successCount,
        failureCount,
        successRate: usageCount > 0 ? successCount / usageCount : 1,
        filePath,
      });
    }

    return rows.sort((a, b) => a.name.localeCompare(b.name));
  }

  async runEvaluationNow(): Promise<EvaluationReport> {
    await this.tracker.load();
    const report = await this.evaluator.evaluate(this.registry.all());
    await this.registry.load({ skillsDir: this.skillsBaseDir });
    return report;
  }
}
