/**
 * skills/skill-evaluator.ts
 * Periodic self-evaluation pass for auto-generated skills.
 */

import { readFile, writeFile } from 'fs/promises';
import type { IProvider } from '../types/provider';
import { createMessage, extractText } from '../types/message';
import type { Skill } from './loader';
import { SkillWriter } from './skill-writer';
import { SkillQualityTracker } from './skill-quality-tracker';
import { createLogger } from '../utils/logger';

const logger = createLogger('skills:evaluator');

export interface EvaluationReport {
  evaluated: number;
  improved: number;
  disabled: number;
  skipped: number;
}

function splitSkillFile(source: string): { frontmatter: string; body: string } | null {
  const match = /^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/m.exec(source.trimStart());
  if (!match?.[1]) return null;
  return { frontmatter: match[1], body: match[2] ?? '' };
}

function setFrontmatterValue(frontmatter: string, key: string, value: string): string {
  const lines = frontmatter.split(/\r?\n/);
  const index = lines.findIndex((line) => line.trim().startsWith(`${key}:`));
  if (index >= 0) lines[index] = `${key}: ${value}`;
  else lines.push(`${key}: ${value}`);
  return lines.join('\n');
}

function stripMarkdownFences(text: string): string {
  return text.replace(/^```(?:markdown|md)?\s*/i, '').replace(/```\s*$/i, '').trim();
}

export class SkillEvaluator {
  private model: string | null = null;

  constructor(
    private readonly provider: IProvider,
    private readonly skillWriter: SkillWriter,
    private readonly tracker: SkillQualityTracker
  ) {}

  private async resolveModel(): Promise<string> {
    if (this.model) return this.model;
    const models = await this.provider.listModels();
    this.model = models[0]?.id ?? 'default';
    return this.model;
  }

  private async disableSkill(skill: Skill): Promise<void> {
    const raw = await readFile(skill.filePath, 'utf-8');
    const split = splitSkillFile(raw);
    if (!split) return;
    const frontmatter = setFrontmatterValue(split.frontmatter, 'enabled', 'false');
    await writeFile(skill.filePath, ['---', frontmatter, '---', '', split.body.trim(), ''].join('\n'), 'utf-8');
  }

  private async improveSkill(skill: Skill, usageCount: number, successCount: number): Promise<void> {
    const model = await this.resolveModel();
    const response = await this.provider.chat({
      model,
      temperature: 0,
      maxTokens: 512,
      messages: [
        createMessage({
          role: 'user',
          content: [
            'You are a skill refinement engine. The following agent skill has a low success rate.',
            'Rewrite ONLY the skill body (the markdown content after the frontmatter) to make it more precise and actionable.',
            'Keep the same purpose. Maximum 800 characters. Return ONLY the new body content, no frontmatter, no explanation.',
            '',
            'Current skill body:',
            skill.body,
            '',
            'Evidence of failures:',
            `The skill has been used ${usageCount} times with only ${successCount} successes.`,
          ].join('\n'),
        }),
      ],
    });

    const newBody = stripMarkdownFences(extractText(response.message.content)).slice(0, 800).trim();
    if (!newBody) return;

    const raw = await readFile(skill.filePath, 'utf-8');
    const split = splitSkillFile(raw);
    if (!split) return;
    await writeFile(skill.filePath, ['---', split.frontmatter, '---', '', newBody, ''].join('\n'), 'utf-8');
    logger.info('skill improved', {
      id: skill.id,
      oldSuccessRate: successCount / usageCount,
      newBody,
    });
  }

  async evaluate(activeSkills: Skill[]): Promise<EvaluationReport> {
    void this.skillWriter;
    const report: EvaluationReport = { evaluated: 0, improved: 0, disabled: 0, skipped: 0 };
    const totalTaskCount = this.tracker.getTaskCounter();

    for (const skill of activeSkills) {
      const isAutoGenerated = skill.frontmatter.auto_generated === true || skill.frontmatter.raw['auto_generated'] === 'true';
      if (!isAutoGenerated) continue;

      report.evaluated += 1;
      const stats = this.tracker.getSkillStats(skill.id);
      if (!stats) {
        report.skipped += 1;
        continue;
      }

      if (stats.usageCount === 0 && totalTaskCount > 20) {
        await this.disableSkill(skill);
        report.disabled += 1;
        logger.info('skill disabled due to no usage', { id: skill.id });
        continue;
      }

      const successRate = stats.usageCount > 0 ? stats.successCount / stats.usageCount : 1;
      if (successRate < 0.6 && stats.usageCount >= 3) {
        await this.improveSkill(skill, stats.usageCount, stats.successCount);
        report.improved += 1;
      } else {
        report.skipped += 1;
      }
    }

    return report;
  }
}
